### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by yshollander-selerity** [sergioaten/msteams-notifications#3]
Hi,

I'm trying to set up sergioaten/msteams-notifications@v0.11-beta in my GH Action, and I am getting the following error message/stack trace:

```
Error: Cannot find module '@actions/core'
Require stack:
- /actions-runner/_work/_actions/sergioaten/msteams-notifications/v0.11-beta/dist/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1028:15)
    at Function.Module._load (node:internal/modules/cjs/loader:873:27)
    at Module.require (node:internal/modules/cjs/loader:1100:19)
    at require (node:internal/modules/cjs/helpers:119:[18](https://github.com/ION-Analytics/selerity-context-tools/actions/runs/8272752698/job/22635222824#step:7:19))
    at Object.617 (/actions-runner/_work/_actions/sergioaten/msteams-notifications/v0.11-beta/dist/index.js:7:33)
    at __nccwpck_require__ (/actions-runner/_work/_actions/sergioaten/msteams-notifications/v0.11-beta/dist/index.js:58:42)
    at /actions-runner/_work/_actions/sergioaten/msteams-notifications/v0.11-beta/dist/index.js:77:14
    at /actions-runner/_work/_actions/sergioaten/msteams-notifications/v0.11-beta/dist/index.js:203:3
    at Object.<anonymous> (/actions-runner/_work/_actions/sergioaten/msteams-notifications/v0.11-beta/dist/index.js:206:12)
    at Module._compile (node:internal/modules/cjs/loader:1[19](https://github.com/ION-Analytics/selerity-context-tools/actions/runs/8272752698/job/22635222824#step:7:20)8:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/actions-runner/_work/_actions/sergioaten/msteams-notifications/v0.11-beta/dist/index.js'
  ]
}

```

I've seen similar issues logged for other plugins.  Is this easy to fix?  

Thanks!

**Comment by logileifs** [comment]
I'm running into the same issue, is there any workaround for this?

**Comment by yshollander-selerity** [comment]
I am thinking this is abandonware :(
